### ISSUE TITLE
Feature request: measurement of the inverse drift rate, dt/dν

### ISSUE THREAD

**Issue by bwmeyers** [danielreardon/scintools#14]
I was wondering if the formalism used within `scintools` is able to also provide a measurement of the scintillation drift rate. This seems to be a relatively interesting value if able to be constrained, since it links directly to the refractive scattering angle. 

I admit to not having carefully read through the implementation here, but perhaps it is something better calculated directly from the ACF? My understanding is that "The proper measure of dt/dν would be the slope of the line joining the points on the ellipse with the highest correlation at a given frequency offset." (Bhat et al. 1998). Is this feasible?

**Comment by danielreardon** [comment]
Sorry for the two month delay @bwmeyers ..

There are already some utilities to calculate the skew in the ACF. The function for the `Dynspec` class, `get_acf_tilt()`, just fits a straight line through the maxima at each frequency lag near the core of the ACF, with the gradient of this line giving the drift rate in units of mins/MHz. It is saved under the `acf_tilt` attribute

Alternatively, the 'acf2d_approx' model for `get_scint_params()` also fits a skew parameter simultaneously with the scintillation bandwidth and timescale. I recently changed the definition so it is also in units of mins/MHz. This one gets saved under the `phasegrad` attribute.

I agree they're very interesting values! I'll keep this issue open because I want to work on these functions a bit more, and do some tests on them.

**Comment by danielreardon** [comment]
@bwmeyers I recently finished a paper using the phase gradients inferred from the drift rates measured with the `get_scint_params(method='acf2d_approx')` function, which is [here](https://ui.adsabs.harvard.edu/abs/2023MNRAS.521.6392R/abstract). So I'd recommend using this for now, but I will eventually also work on other methods
